# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Code/Client/Challenges.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_challenges(object):
    def setupUi(self, challenges):
        challenges.setObjectName("challenges")
        challenges.resize(360, 320)
        challenges.setStyleSheet("QWidget{\n"
"background:#484848;\n"
"}\n"
"QAbstractButton{\n"
"border-style:none;\n"
"border-radius:0px;\n"
"padding:5px;\n"
"color:#DCDCDC;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #858585,stop:1 #383838);\n"
"}\n"
"QAbstractButton:hover{\n"
"color:#000000;\n"
"background-color:#008aff;\n"
"}\n"
"QAbstractButton:pressed{\n"
"color:#DCDCDC;\n"
"border-style:solid;\n"
"border-width:0px 0px 0px 4px;\n"
"padding:4px 4px 4px 2px;\n"
"border-color:#008aff;\n"
"background-color:#444444;\n"
"}\n"
"QAbstractButton:disabled{\n"
"color:#787878;\n"
"background-color:#585858;\n"
"}\n"
"QLabel{\n"
"color:#DCDCDC;\n"
"}\n"
"QTabWidget::pane{\n"
"border:1px solid #383838;\n"
"}\n"
"QTabBar::tab{\n"
"color:#DCDCDC;\n"
"background:#383838;\n"
"padding:6px 10px;\n"
"}\n"
"QTabBar::tab:selected{\n"
"background:#008aff;\n"
"color:#000000;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(challenges)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_hint = QtWidgets.QLabel(self.centralwidget)
        self.label_hint.setWordWrap(True)
        self.label_hint.setObjectName("label_hint")
        self.verticalLayout.addWidget(self.label_hint)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_target_tracking = QtWidgets.QWidget()
        self.tab_target_tracking.setObjectName("tab_target_tracking")
        self.verticalLayout_tt = QtWidgets.QVBoxLayout(self.tab_target_tracking)
        self.verticalLayout_tt.setObjectName("verticalLayout_tt")
        self.row_stop_distance = QtWidgets.QHBoxLayout()
        self.row_stop_distance.setObjectName("row_stop_distance")
        self.label_stop_distance_name = QtWidgets.QLabel(self.tab_target_tracking)
        self.label_stop_distance_name.setObjectName("label_stop_distance_name")
        self.row_stop_distance.addWidget(self.label_stop_distance_name)
        self.slider_stop_distance = QtWidgets.QSlider(self.tab_target_tracking)
        self.slider_stop_distance.setMinimum(10)
        self.slider_stop_distance.setMaximum(100)
        self.slider_stop_distance.setProperty("value", 30)
        self.slider_stop_distance.setOrientation(QtCore.Qt.Horizontal)
        self.slider_stop_distance.setObjectName("slider_stop_distance")
        self.row_stop_distance.addWidget(self.slider_stop_distance)
        self.label_stop_distance_value = QtWidgets.QLabel(self.tab_target_tracking)
        self.label_stop_distance_value.setMinimumSize(QtCore.QSize(30, 0))
        self.label_stop_distance_value.setObjectName("label_stop_distance_value")
        self.row_stop_distance.addWidget(self.label_stop_distance_value)
        self.verticalLayout_tt.addLayout(self.row_stop_distance)
        self.row_speed = QtWidgets.QHBoxLayout()
        self.row_speed.setObjectName("row_speed")
        self.label_tt_speed_name = QtWidgets.QLabel(self.tab_target_tracking)
        self.label_tt_speed_name.setObjectName("label_tt_speed_name")
        self.row_speed.addWidget(self.label_tt_speed_name)
        self.slider_tt_speed = QtWidgets.QSlider(self.tab_target_tracking)
        self.slider_tt_speed.setMinimum(1)
        self.slider_tt_speed.setMaximum(10)
        self.slider_tt_speed.setProperty("value", 5)
        self.slider_tt_speed.setOrientation(QtCore.Qt.Horizontal)
        self.slider_tt_speed.setObjectName("slider_tt_speed")
        self.row_speed.addWidget(self.slider_tt_speed)
        self.label_tt_speed_value = QtWidgets.QLabel(self.tab_target_tracking)
        self.label_tt_speed_value.setMinimumSize(QtCore.QSize(30, 0))
        self.label_tt_speed_value.setObjectName("label_tt_speed_value")
        self.row_speed.addWidget(self.label_tt_speed_value)
        self.verticalLayout_tt.addLayout(self.row_speed)
        self.row_color = QtWidgets.QHBoxLayout()
        self.row_color.setObjectName("row_color")
        self.label_tt_color_name = QtWidgets.QLabel(self.tab_target_tracking)
        self.label_tt_color_name.setObjectName("label_tt_color_name")
        self.row_color.addWidget(self.label_tt_color_name)
        self.Button_TT_Color = QtWidgets.QPushButton(self.tab_target_tracking)
        self.Button_TT_Color.setObjectName("Button_TT_Color")
        self.row_color.addWidget(self.Button_TT_Color)
        self.label_tt_color_swatch = QtWidgets.QLabel(self.tab_target_tracking)
        self.label_tt_color_swatch.setMinimumSize(QtCore.QSize(30, 20))
        self.label_tt_color_swatch.setStyleSheet("background-color:#ff0000; border:1px solid #DCDCDC;")
        self.label_tt_color_swatch.setText("")
        self.label_tt_color_swatch.setObjectName("label_tt_color_swatch")
        self.row_color.addWidget(self.label_tt_color_swatch)
        self.verticalLayout_tt.addLayout(self.row_color)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_tt.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_target_tracking, "")
        self.tab_challenge_2 = QtWidgets.QWidget()
        self.tab_challenge_2.setObjectName("tab_challenge_2")
        self.verticalLayout_c2 = QtWidgets.QVBoxLayout(self.tab_challenge_2)
        self.verticalLayout_c2.setObjectName("verticalLayout_c2")
        self.label_c2_placeholder = QtWidgets.QLabel(self.tab_challenge_2)
        self.label_c2_placeholder.setObjectName("label_c2_placeholder")
        self.verticalLayout_c2.addWidget(self.label_c2_placeholder)
        self.tabWidget.addTab(self.tab_challenge_2, "")
        self.tab_challenge_3 = QtWidgets.QWidget()
        self.tab_challenge_3.setObjectName("tab_challenge_3")
        self.verticalLayout_c3 = QtWidgets.QVBoxLayout(self.tab_challenge_3)
        self.verticalLayout_c3.setObjectName("verticalLayout_c3")
        self.label_c3_placeholder = QtWidgets.QLabel(self.tab_challenge_3)
        self.label_c3_placeholder.setObjectName("label_c3_placeholder")
        self.verticalLayout_c3.addWidget(self.label_c3_placeholder)
        self.tabWidget.addTab(self.tab_challenge_3, "")
        self.tab_challenge_4 = QtWidgets.QWidget()
        self.tab_challenge_4.setObjectName("tab_challenge_4")
        self.verticalLayout_c4 = QtWidgets.QVBoxLayout(self.tab_challenge_4)
        self.verticalLayout_c4.setObjectName("verticalLayout_c4")
        self.label_c4_placeholder = QtWidgets.QLabel(self.tab_challenge_4)
        self.label_c4_placeholder.setObjectName("label_c4_placeholder")
        self.verticalLayout_c4.addWidget(self.label_c4_placeholder)
        self.tabWidget.addTab(self.tab_challenge_4, "")
        self.tab_challenge_5 = QtWidgets.QWidget()
        self.tab_challenge_5.setObjectName("tab_challenge_5")
        self.verticalLayout_c5 = QtWidgets.QVBoxLayout(self.tab_challenge_5)
        self.verticalLayout_c5.setObjectName("verticalLayout_c5")
        self.label_c5_placeholder = QtWidgets.QLabel(self.tab_challenge_5)
        self.label_c5_placeholder.setObjectName("label_c5_placeholder")
        self.verticalLayout_c5.addWidget(self.label_c5_placeholder)
        self.tabWidget.addTab(self.tab_challenge_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonRow = QtWidgets.QHBoxLayout()
        self.buttonRow.setObjectName("buttonRow")
        self.Button_Start = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Start.setObjectName("Button_Start")
        self.buttonRow.addWidget(self.Button_Start)
        self.Button_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Stop.setEnabled(False)
        self.Button_Stop.setObjectName("Button_Stop")
        self.buttonRow.addWidget(self.Button_Stop)
        self.verticalLayout.addLayout(self.buttonRow)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        challenges.setCentralWidget(self.centralwidget)

        self.retranslateUi(challenges)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(challenges)

    def retranslateUi(self, challenges):
        _translate = QtCore.QCoreApplication.translate
        challenges.setWindowTitle(_translate("challenges", "Challenges"))
        self.label_hint.setText(_translate("challenges", "Pick a challenge tab, set its options, then Start."))
        self.label_stop_distance_name.setText(_translate("challenges", "Stop distance (cm)"))
        self.label_stop_distance_value.setText(_translate("challenges", "30"))
        self.label_tt_speed_name.setText(_translate("challenges", "Tracking speed"))
        self.label_tt_speed_value.setText(_translate("challenges", "5"))
        self.label_tt_color_name.setText(_translate("challenges", "Target color"))
        self.Button_TT_Color.setText(_translate("challenges", "Pick Color..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_target_tracking), _translate("challenges", "Target Tracking"))
        self.label_c2_placeholder.setText(_translate("challenges", "Not yet implemented."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_challenge_2), _translate("challenges", "Challenge 2"))
        self.label_c3_placeholder.setText(_translate("challenges", "Not yet implemented."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_challenge_3), _translate("challenges", "Challenge 3"))
        self.label_c4_placeholder.setText(_translate("challenges", "Not yet implemented."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_challenge_4), _translate("challenges", "Challenge 4"))
        self.label_c5_placeholder.setText(_translate("challenges", "Not yet implemented."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_challenge_5), _translate("challenges", "Challenge 5"))
        self.Button_Start.setText(_translate("challenges", "Start"))
        self.Button_Stop.setText(_translate("challenges", "Stop"))
        self.label_status.setText(_translate("challenges", "Idle"))
